plugins {
    id 'com.android.application'
}
android {
    namespace 'com.pijatin.rumahaja.mitra'
    compileSdk 34
    defaultConfig {
        applicationId "com.pijatin.rumahaja.mitra"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "2.6.0"
        resValue "string", "app_name", "Pijat IN Mitra"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }
}
